DROP TABLE IF EXISTS USER;

CREATE TABLE USER (
  id LONG AUTO_INCREMENT  PRIMARY KEY,
  username VARCHAR(250) NOT NULL UNIQUE,
  password VARCHAR(250) NOT NULL,
  status VARCHAR(250) DEFAULT 'Deactivated'
);